export const contextOptions = {
  apiKey: 'cfcc4514d85fff7cb3e2e7ef5dee3b827270d030',
  appId: '',
  plugins: {
    // edge-currency-accountbased:
    // eos: true,
    // ethereum: {},
    // fio: true,
    // stellar: true,
    // ripple: true,
    // tezos: true,
    // binance: true,
    // rsk: true,
    // edge-currency-bitcoin:
    bitcoin: true,
    bitcoincash: true,
    bitcoincashtestnet: false,
    bitcoingold: true,
    bitcoingoldtestnet: false,
    bitcoinsv: true,
    bitcointestnet: true,
    dash: true,
    digibyte: true,
    dogecoin: true,
    eboost: true,
    feathercoin: true,
    groestlcoin: true,
    litecoin: true,
    qtum: true,
    ravencoin: true,
    smartcash: true,
    ufo: true,
    vertcoin: true,
    zcoin: true,
    // edge-currency-monero:
    monero: {},
  },
}
